// icons.test.ts — the install-path verification gate (PLAN.md Story 11 P2). The manifest and
// its PNGs are committed artefacts, regenerated by `pnpm --filter @wynding/web gen:icons`
// and NOT rebuilt by `verify`/`build`. That only stays safe if something checks what is
// actually committed, so this test decodes the real PNG bytes with `pngjs` (already a
// devDependency) and reads the real manifest JSON:
//
//   - every manifest icon entry points at a committed file with matching dimensions;
//   - `start_url`/`scope` are RELATIVE, so an installed app opens the deployed base path
//     (`/play/` in production) rather than the origin root;
//   - the apple-touch-icon is fully opaque (iOS composites it onto its own background and
//     renders transparency as black);
//   - the maskable icon keeps every non-background pixel inside the W3C safe zone — the
//     CENTRED CIRCLE of radius 40% of the icon size. A square check would wrongly admit the
//     corners, which are exactly what a circular platform mask crops away.

import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { describe, it, expect } from 'vitest';
import { PNG } from 'pngjs';

const WEB_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC_DIR = path.join(WEB_ROOT, 'public');
const ICONS_DIR = path.join(PUBLIC_DIR, 'icons');

interface ManifestIcon {
  src: string;
  sizes: string;
  type: string;
  purpose: string;
}
interface Manifest {
  name: string;
  short_name: string;
  start_url: string;
  scope: string;
  display: string;
  icons: ManifestIcon[];
}

const manifest = JSON.parse(
  readFileSync(path.join(PUBLIC_DIR, 'manifest.webmanifest'), 'utf8'),
) as Manifest;

const readIcon = (file: string): PNG => PNG.sync.read(readFileSync(path.join(ICONS_DIR, file)));

/** The ground colour every icon is painted on (`--wy-bg`), as an RGB triple. */
const GROUND: readonly [number, number, number] = [0x0d, 0x1b, 0x2a];

/** Antialiasing tolerance. A rasterised edge blends artwork into the ground over a pixel or
 *  two, so a pixel within this channel distance of the ground counts as background — without
 *  it, the safe-zone check would flag the feathered rim of a shape that is genuinely inside. */
const GROUND_TOLERANCE = 12;

function isGround(png: PNG, x: number, y: number): boolean {
  const i = (png.width * y + x) << 2;
  return (
    Math.abs((png.data[i] as number) - GROUND[0]) <= GROUND_TOLERANCE &&
    Math.abs((png.data[i + 1] as number) - GROUND[1]) <= GROUND_TOLERANCE &&
    Math.abs((png.data[i + 2] as number) - GROUND[2]) <= GROUND_TOLERANCE
  );
}

describe('manifest schema (PLAN.md P2)', () => {
  it('declares a RELATIVE start_url and scope, so an installed app opens the deployed base path', () => {
    // Production builds with `vite build --base=/play/` and the deployed HTML links
    // `/play/manifest.webmanifest`; relative members resolve against the MANIFEST URL, so
    // "." is `/play/` there and `/` in dev. A root-absolute "/" would launch the installed
    // app at the origin root — a blank page in production.
    expect(manifest.start_url).toBe('.');
    expect(manifest.scope).toBe('.');
    expect(manifest.start_url.startsWith('/')).toBe(false);
    expect(manifest.scope.startsWith('/')).toBe(false);
  });

  it('is installable: a name, a short_name, and a standalone display mode', () => {
    expect(manifest.name).toBe('Wynding');
    expect(manifest.short_name.length).toBeGreaterThan(0);
    expect(manifest.display).toBe('standalone');
  });

  it('declares the 192/512 "any" icons plus a 512 maskable one', () => {
    const byPurpose = (purpose: string): ManifestIcon[] =>
      manifest.icons.filter((i) => i.purpose === purpose);
    expect(
      byPurpose('any')
        .map((i) => i.sizes)
        .sort(),
    ).toEqual(['192x192', '512x512']);
    expect(byPurpose('maskable').map((i) => i.sizes)).toEqual(['512x512']);
    // Icon srcs are relative too, for the same reason as start_url/scope.
    for (const icon of manifest.icons) {
      expect(icon.src.startsWith('/'), `${icon.src} must be relative`).toBe(false);
      expect(icon.type).toBe('image/png');
    }
  });

  it('every declared icon exists on disk at exactly its declared size', () => {
    for (const icon of manifest.icons) {
      const file = path.join(PUBLIC_DIR, icon.src);
      expect(existsSync(file), `${icon.src} is declared but not committed`).toBe(true);
      const png = PNG.sync.read(readFileSync(file));
      const [w, h] = icon.sizes.split('x').map(Number);
      expect(png.width, `${icon.src} width`).toBe(w);
      expect(png.height, `${icon.src} height`).toBe(h);
    }
  });
});

describe('committed icon PNGs (PLAN.md P2)', () => {
  it('the apple-touch-icon is 180×180 and FULLY opaque (iOS renders transparency as black)', () => {
    const png = readIcon('apple-touch-icon.png');
    expect(png.width).toBe(180);
    expect(png.height).toBe(180);
    let transparent = 0;
    for (let i = 3; i < png.data.length; i += 4) {
      if (png.data[i] !== 255) transparent++;
    }
    expect(transparent, `${transparent} non-opaque pixels in apple-touch-icon.png`).toBe(0);
  });

  it('the maskable icon keeps all artwork inside the safe zone (a CIRCLE of radius 40%)', () => {
    const png = readIcon('icon-maskable-512.png');
    const cx = png.width / 2;
    const cy = png.height / 2;
    const safeRadius = png.width * 0.4;
    const outside: string[] = [];
    for (let y = 0; y < png.height && outside.length < 5; y++) {
      for (let x = 0; x < png.width; x++) {
        const dx = x + 0.5 - cx;
        const dy = y + 0.5 - cy;
        if (dx * dx + dy * dy <= safeRadius * safeRadius) continue; // inside the safe zone
        if (!isGround(png, x, y)) {
          outside.push(`(${x},${y})`);
          break;
        }
      }
    }
    expect(
      outside,
      `artwork outside the maskable safe-zone circle at ${outside.join(' ')}`,
    ).toEqual([]);
  });

  it('the maskable icon actually PAINTS its mark (the safe-zone check cannot pass by being blank)', () => {
    const png = readIcon('icon-maskable-512.png');
    let painted = 0;
    for (let y = 0; y < png.height; y += 4) {
      for (let x = 0; x < png.width; x += 4) {
        if (!isGround(png, x, y)) painted++;
      }
    }
    const sampled = Math.ceil(png.height / 4) * Math.ceil(png.width / 4);
    expect(painted / sampled, 'the maskable icon looks blank').toBeGreaterThan(0.05);
  });

  it('the "any" icons fill their canvas edge to edge (no pre-baked safe-zone padding)', () => {
    // The plain icons are shown as-is, so they should use the full square — a corner still
    // reads as the navy ground, but the artwork sits well outside the 40% circle that the
    // maskable variant is confined to.
    for (const file of ['icon-192.png', 'icon-512.png']) {
      const png = readIcon(file);
      const cx = png.width / 2;
      const cy = png.height / 2;
      const safeRadius = png.width * 0.4;
      let outsideCircle = 0;
      for (let y = 0; y < png.height; y++) {
        for (let x = 0; x < png.width; x++) {
          const dx = x + 0.5 - cx;
          const dy = y + 0.5 - cy;
          if (dx * dx + dy * dy <= safeRadius * safeRadius) continue;
          if (!isGround(png, x, y)) outsideCircle++;
        }
      }
      expect(outsideCircle, `${file} does not use its full canvas`).toBeGreaterThan(0);
    }
  });
});
